version: '3.9'

services:
  code_base:
    #build: .
    image: uafridi/codebase_bankcustomerchurnprediction_ols
    volumes:
      - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/codeBase/ && mkdir -p /tmp/codeBase/ && cp -r /codeBase/ /tmp/;

volumes:
  ai_system:
    external: true
