# Dockerfile for activationBase
FROM busybox

# Copy activation data into the image
COPY ../../data/customer_churn_dataset/activation_data.csv /tmp/activationBase/

# Add the README file
COPY images/activationBase_BankCustomerChurnPrediction/Readme.md /tmp/activationBase/

# Set working directory
#WORKDIR /tmp/activationBase
